# Copyright 2022 Pekka Enberg and contributors
# SPDX-License-Identifier: MIT

[package]
name = "tsparser_parser"
version = "0.0.0"
authors = ["Pekka Enberg"]
edition = "2021"
license = "MIT"

[lib]
path = "lib.rs"

[dependencies]
utf8-chars = "1.0.2"
